# Generated by Django 2.1.2 on 2018-10-20 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('tiny_url', models.CharField(max_length=5, unique=True)),
                ('url', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'ordering': ('created',),
            },
        ),
    ]
