# Generated by Django 2.1.2 on 2018-10-20 02:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='record',
            old_name='url',
            new_name='old_url',
        ),
    ]
