# Generated by Django 2.1.2 on 2018-10-20 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20181020_0237'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='old_url',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='record',
            name='tiny_url',
            field=models.CharField(blank=True, max_length=5),
        ),
    ]
