# Generated by Django 2.1.2 on 2018-10-20 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20181020_0415'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='old_url',
            field=models.CharField(max_length=500),
        ),
    ]
